export const initialProfessionals = [
  {
    id: "marla-hursig",
    name: "Marla Hursig",
    businessName: "The Honest Image",
    specialty: "Make-up & Style Consultations",
    category: "fashion",
    phone: "(505) 250-5335",
    email: "marla@thehonestimage.com",
    website: "https://thehonestimage.com",
    bio: "Marla Hursig is a makeup artist and style consultant dedicated to helping individuals discover and project their most authentic selves. Through personalized color analysis and wardrobe alignment, she empowers her clients to step out in confidence.",
    imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&q=80&w=600",
    businessUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&q=80&w=600",
    logoUrl: "https://i3.createsend1.com/ei/r/23/046/C81/002230/csfinal/thehonestimage-logos-rgb_primary-kliegel_stulips-99000003cf01453c.png",
    isFeatured: true,
    status: "active",
    instagram: "@thehonestimage",
    specialOffer: "Free 15-minute style discovery call"
  },
  {
    id: "nikki-roiz",
    name: "Nikki Roiz",
    businessName: "Zior Skin & Body",
    specialty: "Aesthetic Skin & Body Therapy",
    category: "face-skin",
    phone: "(505) 377-8457",
    email: "nikki@ziorskin.com",
    website: "https://ziorskin.com",
    bio: "Nikki Roiz is a master esthetician specializing in advanced skin therapies, body contouring, and customized facials. At Zior Skin & Body, she merges medical-grade technologies with relaxing rituals for transformative results.",
    imageUrl: "https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&q=80&w=600",
    businessUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=600",
    logoUrl: "https://i5.createsend1.com/ei/r/23/046/C81/002230/csfinal/cropped-Zior-Skin-Body-Logo_2000px-120x108-990000028a01453c.png",
    isFeatured: false,
    status: "active",
    instagram: "@ziorskinbody",
    specialOffer: "$20 off your first facial treatment"
  },
  {
    id: "daniel-paterno",
    name: "Daniel Paterno",
    businessName: "Daniel Paterno Hair @ Kabeyo Beauty",
    specialty: "Precision Haircutting & Coloring",
    category: "hair",
    phone: "(219) 413-2278",
    email: "daniel@kabeyobeauty.com",
    website: "https://kabeyobeauty.com",
    bio: "Daniel Paterno is a precision haircutting and dimensional color expert. Located at Kabeyo Beauty, Daniel creates custom-crafted hairstyles that flow naturally with the client's facial structure and lifestyle.",
    imageUrl: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=600",
    businessUrl: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&q=80&w=600",
    logoUrl: "https://i7.createsend1.com/ei/r/23/046/C81/002230/csfinal/DanielPaternoHairatKabeyoBeauty-99028a06db01453c.png",
    isFeatured: true,
    status: "active",
    instagram: "@danielpaternohair",
    specialOffer: "Complimentary deep conditioning with any color service"
  },
  {
    id: "christie-rein",
    name: "Christie Rein",
    businessName: "Feel Alive",
    specialty: "Integrative Health & Wellness Coaching",
    category: "health-wellness",
    phone: "(505) 315-4786",
    email: "christie@feelalivehealth.com",
    website: "https://feelalivehealth.com",
    bio: "Christie Rein is a certified health coach who guides individuals to reclaim their energy, sleep better, and find balance. She focuses on sustainable lifestyle changes that make clients truly 'feel alive' inside and out.",
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=600",
    businessUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=600",
    logoUrl: "https://i2.createsend1.com/ei/r/03/2E6/7B0/055313/csfinal/471432689_10162651205954534_1198793115116818507_n-3b5e78ee28ba7bcc.jpg",
    isFeatured: false,
    status: "active",
    instagram: "@feelalivecoaching",
    specialOffer: "Free 30-minute metabolic health assessment"
  },
  {
    id: "miriam-ortiz-y-pino",
    name: "Miriam Ortiz y Pino",
    businessName: "More than Organized",
    specialty: "Professional Organizing & Coaching",
    category: "lifestyle",
    phone: "(505) 243-4356",
    email: "miriam@morethanorganized.net",
    website: "https://morethanorganized.net",
    bio: "Miriam Ortiz y Pino is a professional organizer and business coach who helps busy entrepreneurs design systems to clear physical clutter, streamline mental loads, and create workspace environments that maximize productivity.",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600",
    businessUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
    logoUrl: "https://i3.createsend1.com/ei/r/65/9FB/5F1/065853/csfinal/46230751_10156303830985376_5942540622173831168_n-caebb9c79bbab66.jpg",
    isFeatured: false,
    status: "active",
    instagram: "@morethanorganized",
    specialOffer: "10% off your initial home or office alignment package"
  },
  {
    id: "deanna-vincent",
    name: "DeAnna Vincent",
    businessName: "Dry Heat Photography",
    specialty: "High-End Portrait & Brand Photography",
    category: "photography",
    phone: "(505) 414-9039",
    email: "deanna@dryheatphoto.com",
    website: "https://dryheatphoto.com",
    bio: "DeAnna Vincent captures the soulful, vibrant essence of New Mexico. Specializing in branding portraits for beauty and lifestyle professionals, she creates visual assets that tell a compelling business story.",
    imageUrl: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&q=80&w=600",
    businessUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=600",
    logoUrl: "https://i4.createsend1.com/ei/r/65/9FB/5F1/065853/csfinal/DeAnna0020-3-f0e01f219212485e.jpg",
    isFeatured: false,
    status: "active",
    instagram: "@dryheatphotography",
    specialOffer: "10% off custom personal branding headshot sessions"
  }
];
